services:
  web:
    image: dilshod1405/vchdbuxoro
    container_name: vchdbuxoro
    restart: always
    env_file:
      - .env
    ports:
      - "8006:8000"
    command: ["sh", "/app/entrypoint.sh"]

