version: "3.9"

services:
  web:
    image: $DOCKER_USERNAME/vchdbuxoro:latest  # Remote image used in production
    container_name: vchdbuxoro
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["sh", "/app/entrypoint.sh"]

  db:
    image: postgres:16-alpine
    container_name: vchdbuxorodb
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
