services:
  web:
    image: dilshod1405/vchdbuxoro
    container_name: vchdbuxoro
    restart: always
    env_file:
      - .env
    ports:
      - "8006:8000"
    command: ["sh", "/app/entrypoint.sh"]
    depends_on:
      - db

  db:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

volumes:
  postgres_data: