# Generated by Django 5.2.1 on 2025-05-25 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=9, verbose_name='Telefon raqami'),
        ),
    ]
